### ISSUE TITLE
Don't know how to use it ?

### ISSUE THREAD

**Issue by qingyun1029** [tkareine/jekyll-minibundle#9]
I have done the following 

**step 1**:Install jekyll-minibundle

```
$ gem install jekyll-minibundle
```

**step 2**: Adding this line to the _config.yml file of my Jekyll site project
```
gems:
  - jekyll-paginate
  - jekyll-paginate-category
  - jekyll-toc
  - 'jekyll/minibundle' # adding this line
safe: false
# gems: [jekyll-paginate, jekyll-paginate-category]

```

and Adding this line to the Gemfile 

```
gem "jekyll-paginate"
gem "jekyll-paginate-category"
gem "pygments.rb"
gem "jekyll-toc"
gem "jekyll/minibundle" # adding this line
```

executing command 'jekyll build', it throw err, 

```
C:\Users\dell\Desktop\MyBlog>jekyll build
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/resolver.rb:36
6:in `block in verify_gemfile_dependencies_are_found!': Could not find gem 'jeky
ll/minibundle x64-mingw32' in any of the gem sources listed in your Gemfile or a
vailable on this machine. (Bundler::GemNotFound)
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/r
esolver.rb:341:in `each'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/r
esolver.rb:341:in `verify_gemfile_dependencies_are_found!'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/r
esolver.rb:199:in `start'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/r
esolver.rb:181:in `resolve'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/d
efinition.rb:250:in `resolve'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/d
efinition.rb:174:in `specs'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/d
efinition.rb:233:in `specs_for'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/d
efinition.rb:222:in `requested_specs'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/r
untime.rb:118:in `block in definition_method'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/r
untime.rb:19:in `setup'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler.r
b:99:in `setup'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/jekyll-3.3.1/lib/jekyll/plug
in_manager.rb:36:in `require_from_bundler'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/jekyll-3.3.1/exe/jekyll:9:in
 `<top (required)>'
        from C:/Ruby23-x64/bin/jekyll:23:in `load'
        from C:/Ruby23-x64/bin/jekyll:23:in `<main>'
```

Am I getting wrong something? 

Thanks for you !

**Comment by tkareine** [comment]
In your Gemfile, try replacing the line

```
gem "jekyll/minibundle"
```

with

```
gem "jekyll-minibundle"
```

**Comment by qingyun1029** [comment]
I just started using jekyll , Thank you very much for your help !!!

I have dealt with this problem !

**Comment by tkareine** [comment]
👍
